version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - HOST=0.0.0.0
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
