name: Continuos Delivery

on:
  release:
    types: [published]

jobs:
  publish-to-npm:
    name: Publish to NPM Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.1

      - name: NPM Install
        run: npm install

      - name: Publish to registry
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

  publish-to-github-packages:
    name: Publish to Github Packages
    needs: publish-to-npm
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14.16.1
          registry-url: 'https://npm.pkg.github.com'
          scope: '@luisfalconmx'
      - run: npm install --only=production
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
