name: Continuos Delivery

on:
  release:
    types: [published]

jobs:
  publish-to-npm:
    name: Publish to NPM Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: 'componetizer-cli'

      - name: Set enviroment variables
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Change npm package version
        uses: reedyuk/npm-version@1.1.1
        with:
          version: ${{ env.RELEASE_VERSION }}

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.1

      - name: NPM Install
        run: npm install

      - name: Publish to registry
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

  publish-to-github-packages:
    name: Publish to Github Packages
    needs: publish-to-npm
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14.16.1
          registry-url: 'https://npm.pkg.github.com'
          scope: '@componetizer'
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
