name: Continuos Delivery

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.4

      - run: npm install

      - name: Publish to NPM Registry
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Publish to Github Package Registry
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.REPOSITORY_TOKEN }}
          registry: https://npm.pkg.github.com/
