name: Continuos Integration

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        language: ['javascript']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v1

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

  audit:
    name: Audit
    needs: analyze
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: npm install
      - uses: oke-py/npm-audit-action@v1.7.1
        with:
          github_token: ${{ secrets.REPOSITORY_TOKEN }}
          issue_assignees: luisfalconmx
          issue_labels: vulnerability

  release:
    name: Release Draft
    needs: audit
    runs-on: ubuntu-20.04
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
